version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
    time: '00:00'
    timezone: UTC
  labels:
    - dependencies
  rebase-strategy: auto
  open-pull-requests-limit: 32
  reviewers:
    - BadwaterBay/maintainers
